services:
  backend:
    build: ./backend
    container_name: fleet_backend
    restart: always
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
    ports:
      - "5002:5000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
    depends_on:
      - mongo
    networks:
      - fleetnet

  frontend:
    build: 
      context: ./frontend
      target: development
    container_name: fleet_frontend
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "3002:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - fleetnet

  mongo:
    image: mongo:7.0
    platform: linux/arm64
    container_name: fleet_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fleetnet

networks:
  fleetnet:

volumes:
  mongo_data:
